export const Status_Code = {
    ERROR_CODE: {
        BAD_REQUEST: "400",
        NOT_FOUND: "404",
        ALREADY_EXISTS: "409",
        INVALID_CREDENTIALS: '401',
        UNAUTHORIZED: '403',
        CONFIRM_PASSWORD_NOT_MATCHED: "422",
        INTERNAL_SERVER_ERROR: "500",
        CATEGORY_NOT_FOUND: "404",
        CATEGORY_ALREADY_EXISTS: "409",

        PRODUCT_NOT_FOUND: "404",
        PRODUCT_ALREADY_EXISTS: "409",

        ORDER_NOT_FOUND: "404",
        ORDER_ALREADY_EXISTS: "409",
        INSUFFICIENT_QUANTITY: "400",
    },
    SUCCESS_CODE: {
        CREATED_SUCCESSFULLY: "201",
        UPDATED_SUCCESSFULLY: "200",
        DELETED_SUCCESSFULLY: "204",
        LOGIN_SUCCESSFUL: '200',
        LOGOUT_SUCCESSFUL: '204',
    },
};